In [44]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import re

In [45]:
# create dataframe
df = pd.DataFrame(columns = ['card name', 'card number', 'card expansion', 'card type', 'card rarity'])
index = 0
num_Pages = 556

# iterate over every page on website
for i in range(num_Pages+1):
    
    # collect all HTML from page
    web_url = 'https://www.tcgcollector.com/cards/intl?page={}'.format(i)
    source = requests.get(web_url).text
    soup = BeautifulSoup(source, 'lxml')

    # iterate over every row on page, and find the text for every column
    for row in soup.find_all('div', class_='card-list-item card-search-result-card'):
        card_Name = row.find('div', class_='card-list-item-entry card-list-item-card-name').text.strip()
        card_Number = row.find('div', class_='card-list-item-entry card-list-item-card-number').text.strip()
        card_Expansion = row.find('div', class_='card-list-item-entry card-list-item-expansion').text.strip()
        card_Type = row.find('div', class_='card-list-item-entry card-list-item-type').text.strip()
        card_Rarity = row.find('div', class_='card-list-item-entry card-list-item-rarity').text.strip()
        df.loc[index] = [card_Name, card_Number, card_Expansion, card_Type, card_Rarity]
        index += 1

In [46]:
df

,card name,card number,card expansion,card type,card rarity
0,Weedle,001/185,Vivid Voltage,Basic,Common
1,Kakuna,002/185,Vivid Voltage,Stage 1,Uncommon
2,Beedrill,003/185,Vivid Voltage,Stage 2,Rare
3,Exeggcute,004/185,Vivid Voltage,Basic,Common
4,Exeggutor,005/185,Vivid Voltage,Stage 1,Rare
...,...,...,...,...,...
13908,"Articuno, Moltres, and Zapdos",—,Unnumbered Promos,Basic,—
13909,Zorua and Celebi,—,Unnumbered Promos,Basic,Promo
13910,Zoroark and Legendary Pokémon,—,Unnumbered Promos,Basic,Promo
13911,"Tornadus, Thundurus & Landorus",—,Unnumbered Promos,Basic,Promo
13912,No. 2 Trainer (2018),—,Unnumbered Promos,Item,—